<a href="https://colab.research.google.com/github/jai21-7/Introduction-to-Pytorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
print("Hello Im excited to learn PyTorch")

Hello Im excited to learn PyTorch


In [28]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


Introduction to tensors

creating tensor


## Introduction to tensors
###Creating tensors
Pytorch are created using 'torch.Tensor()' -= https://docs.pytorch.org/tutorials/beginner/basics/intro.html

In [29]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [30]:
scalar.ndim

0

In [31]:
#Get tensor back as python int
scalar.item()


7

In [32]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [33]:
vector.ndim

1

In [34]:
vector.shape

torch.Size([2])

In [35]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [36]:
MATRIX.ndim

2

In [37]:
MATRIX[1]

tensor([ 9, 10])

In [38]:
MATRIX.shape



torch.Size([2, 2])

In [39]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6,9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [40]:
TENSOR.ndim

3

In [41]:
TENSOR.shape

torch.Size([1, 3, 3])

In [42]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.



' Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [43]:
# Create a Random tensors of size (3,4)

random_tensor = torch.rand(3, 4)
random_tensor




tensor([[0.5463, 0.9701, 0.0484, 0.9792],
        [0.3367, 0.6005, 0.0919, 0.5409],
        [0.9369, 0.6343, 0.1541, 0.0348]])

In [44]:
random_tensor.ndim

2

In [45]:
# Create a random tensor with  similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim
#


(torch.Size([224, 224, 3]), 3)


https://docs.pytorch.org/tutorials/beginner/pytorch_with_examples.html




In [46]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [47]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
ones.dtype

torch.float32

In [49]:
random_tensor.dtype


torch.float32

In [50]:
### Creating a range of tensor and tensor-like

In [52]:
# Use torch.range
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# Use torch.range() and get deprecated message, use torch.arrange
one_to_ten = torch.arange(start=1, end=1111, step=11)
one_to_ten

tensor([   1,   12,   23,   34,   45,   56,   67,   78,   89,  100,  111,  122,
         133,  144,  155,  166,  177,  188,  199,  210,  221,  232,  243,  254,
         265,  276,  287,  298,  309,  320,  331,  342,  353,  364,  375,  386,
         397,  408,  419,  430,  441,  452,  463,  474,  485,  496,  507,  518,
         529,  540,  551,  562,  573,  584,  595,  606,  617,  628,  639,  650,
         661,  672,  683,  694,  705,  716,  727,  738,  749,  760,  771,  782,
         793,  804,  815,  826,  837,  848,  859,  870,  881,  892,  903,  914,
         925,  936,  947,  958,  969,  980,  991, 1002, 1013, 1024, 1035, 1046,
        1057, 1068, 1079, 1090, 1101])

https://docs.pytorch.org/docs/stable/generated/torch.arange.html

In [57]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0])