<a href="https://colab.research.google.com/github/jai21-7/Introduction-to-Pytorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello Im excited to learn PyTorch")

Hello Im excited to learn PyTorch


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


Introduction to tensors

creating tensor


## Introduction to tensors
###Creating tensors
Pytorch are created using 'torch.Tensor()' -= https://docs.pytorch.org/tutorials/beginner/basics/intro.html

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as python int
scalar.item()


7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape



torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6,9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.



' Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [17]:
# Create a Random tensors of size (3,4)

random_tensor = torch.rand(3, 4)
random_tensor




tensor([[0.1704, 0.5084, 0.7283, 0.7998],
        [0.9359, 0.2511, 0.0765, 0.7262],
        [0.0686, 0.1823, 0.4483, 0.5369]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with  similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim
#


(torch.Size([224, 224, 3]), 3)


https://docs.pytorch.org/tutorials/beginner/pytorch_with_examples.html




In [20]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype


torch.float32

In [24]:
### Creating a range of tensor and tensor-like

In [25]:
# Use torch.range
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Use torch.range() and get deprecated message, use torch.arrange
one_to_ten = torch.arange(start=1, end=1111, step=11)
one_to_ten

tensor([   1,   12,   23,   34,   45,   56,   67,   78,   89,  100,  111,  122,
         133,  144,  155,  166,  177,  188,  199,  210,  221,  232,  243,  254,
         265,  276,  287,  298,  309,  320,  331,  342,  353,  364,  375,  386,
         397,  408,  419,  430,  441,  452,  463,  474,  485,  496,  507,  518,
         529,  540,  551,  562,  573,  584,  595,  606,  617,  628,  639,  650,
         661,  672,  683,  694,  705,  716,  727,  738,  749,  760,  771,  782,
         793,  804,  815,  826,  837,  848,  859,  870,  881,  892,  903,  914,
         925,  936,  947,  958,  969,  980,  991, 1002, 1013, 1024, 1035, 1046,
        1057, 1068, 1079, 1090, 1101])

https://docs.pytorch.org/docs/stable/generated/torch.arange.html

In [27]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0])

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

https://docs.pytorch.org/docs/stable/tensors.html

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:

1. Tensors not right datatype
2. Tensors right device
3. Tensors not on the right device

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors
1. Tensors not right datatype-to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors right device-to get device from a tensor, can use 'tensor.device'
3. Tensors not on the right device-if tensor is on a different device, can use 'tensor.to(device)'


In [34]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8301, 0.5421, 0.7547, 0.7565],
        [0.6269, 0.8816, 0.0510, 0.0091],
        [0.3853, 0.7134, 0.3097, 0.9039]])

In [35]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8301, 0.5421, 0.7547, 0.7565],
        [0.6269, 0.8816, 0.0510, 0.0091],
        [0.3853, 0.7134, 0.3097, 0.9039]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manipulating Tensors (tensor operations)

Tensor operations include:

.Addition

.Subtraction

.Multiplication(element-wise)

.Division

.Matrix multiplication

In [36]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
#Substract 10
tensor - 10

tensor([-9, -8, -7])

In [40]:
#Try out Pytorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication

2. Matrix multiplication(dot product)


There are two main rules that performing matrix multiplication needs to satisfy

1. The **inner dimensions** must match:

* ` (3, 2) @ (3, 2)` won't work
* ` (2, 3) @ (3, 2)` will work
* ` (3, 2) @ (2, 3)` will work

The resulting matrix has the shape of the **outer dimensions**:

* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` ->` (3, 3)`


https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [41]:
tensor * tensor

tensor([1, 4, 9])

In [42]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
#Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
#Matrix Multiplication by hand
1*1 + 2*2 + 3*3

14

In [45]:
tensor @ tensor

tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)

tensor(1)
tensor(5)
tensor(14)
CPU times: user 832 µs, sys: 151 µs, total: 983 µs
Wall time: 1.02 ms


In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 495 µs, sys: 90 µs, total: 585 µs
Wall time: 364 µs


tensor(14)

One of the most common errors in deep learning: shape error

http://matrixmultiplication.xyz/

In [48]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [49]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A transpose switches the axes or dimensions of a given tensor.

In [50]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [51]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [52]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [53]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [56]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Finding the min, max, mean, sum,etc(tensor aggregation)

In [60]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [58]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [59]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [61]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [62]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Finding the positional min and max

In [64]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
# Find the position in tensor that has the minimum value with argmin() -> return index
x.argmin()

tensor(0)

In [67]:
x[0]

tensor(0)

In [68]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [69]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsequeezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

https://docs.pytorch.org/docs/stable/generated/torch.stack.html

https://docs.pytorch.org/docs/stable/generated/torch.vstack.html

https://docs.pytorch.org/docs/stable/generated/torch.hstack.html

In [71]:
#Let's create a tensor
import torch
x = torch.arange(1., 10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [72]:
# Add a extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
#Change the view
z=x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [74]:
# Changing z changes x(because a view of a tensor shares the same memory as the orignal)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [75]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [76]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [78]:
x_stacked = torch.stack([x, x, x, x], dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Torch Squeeze

x = torch.zeros(2, 1, 2, 1, 2)

x.size()

y = torch.squeeze(x)

y.size()

y = torch.squeeze(x, 0)

y.size()

y = torch.squeeze(x, 1)

y.size()

y = torch.squeeze(x, (1, 2, 3))





https://docs.pytorch.org/docs/stable/generated/torch.squeeze.html

In [84]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")
#

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [87]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [79]:
x_reshaped.shape

torch.Size([1, 9])

In [82]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [83]:
x_reshaped.squeeze().shape

torch.Size([9])

In [91]:
# torch.permute - rearranges the dimensions of a target tensor in a sprcified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


https://docs.pytorch.org/docs/stable/generated/torch.permute.html

In [94]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

### Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [95]:
#Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [96]:
# Let's index on pur new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [97]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [98]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

3:27:48