<a href="https://colab.research.google.com/github/jai21-7/Introduction-to-Pytorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
print("Hello Im excited to learn PyTorch")

Hello Im excited to learn PyTorch


In [62]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


Introduction to tensors

creating tensor


## Introduction to tensors
###Creating tensors
Pytorch are created using 'torch.Tensor()' -= https://docs.pytorch.org/tutorials/beginner/basics/intro.html

In [63]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [64]:
scalar.ndim

0

In [65]:
#Get tensor back as python int
scalar.item()


7

In [66]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [67]:
vector.ndim

1

In [68]:
vector.shape

torch.Size([2])

In [69]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [70]:
MATRIX.ndim

2

In [71]:
MATRIX[1]

tensor([ 9, 10])

In [72]:
MATRIX.shape



torch.Size([2, 2])

In [73]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6,9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [74]:
TENSOR.ndim

3

In [75]:
TENSOR.shape

torch.Size([1, 3, 3])

In [76]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.



' Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [77]:
# Create a Random tensors of size (3,4)

random_tensor = torch.rand(3, 4)
random_tensor




tensor([[0.3820, 0.5082, 0.9683, 0.9661],
        [0.0327, 0.6065, 0.5919, 0.7141],
        [0.3966, 0.8906, 0.2967, 0.4893]])

In [78]:
random_tensor.ndim

2

In [79]:
# Create a random tensor with  similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim
#


(torch.Size([224, 224, 3]), 3)


https://docs.pytorch.org/tutorials/beginner/pytorch_with_examples.html




In [80]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [81]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [82]:
ones.dtype

torch.float32

In [83]:
random_tensor.dtype


torch.float32

In [84]:
### Creating a range of tensor and tensor-like

In [85]:
# Use torch.range
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
# Use torch.range() and get deprecated message, use torch.arrange
one_to_ten = torch.arange(start=1, end=1111, step=11)
one_to_ten

tensor([   1,   12,   23,   34,   45,   56,   67,   78,   89,  100,  111,  122,
         133,  144,  155,  166,  177,  188,  199,  210,  221,  232,  243,  254,
         265,  276,  287,  298,  309,  320,  331,  342,  353,  364,  375,  386,
         397,  408,  419,  430,  441,  452,  463,  474,  485,  496,  507,  518,
         529,  540,  551,  562,  573,  584,  595,  606,  617,  628,  639,  650,
         661,  672,  683,  694,  705,  716,  727,  738,  749,  760,  771,  782,
         793,  804,  815,  826,  837,  848,  859,  870,  881,  892,  903,  914,
         925,  936,  947,  958,  969,  980,  991, 1002, 1013, 1024, 1035, 1046,
        1057, 1068, 1079, 1090, 1101])

https://docs.pytorch.org/docs/stable/generated/torch.arange.html

In [87]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0])

In [95]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

https://docs.pytorch.org/docs/stable/tensors.html

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:

1. Tensors not right datatype
2. Tensors right device
3. Tensors not on the right device

In [91]:
float_32_tensor.dtype

torch.float32

In [96]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [98]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [99]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [100]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors
1. Tensors not right datatype-to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors right device-to get device from a tensor, can use 'tensor.device'
3. Tensors not on the right device-if tensor is on a different device, can use 'tensor.to(device)'


In [102]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7455, 0.7219, 0.1091, 0.6712],
        [0.1576, 0.3861, 0.3920, 0.2274],
        [0.1057, 0.5607, 0.8143, 0.0588]])

In [103]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7455, 0.7219, 0.1091, 0.6712],
        [0.1576, 0.3861, 0.3920, 0.2274],
        [0.1057, 0.5607, 0.8143, 0.0588]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manipulating Tensors (tensor operations)

Tensor operations include:

.Addition

.Subtraction

.Multiplication(element-wise)

.Division

.Matrix multiplication

In [104]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [105]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [106]:
tensor

tensor([1, 2, 3])

In [107]:
#Substract 10
tensor - 10

tensor([-9, -8, -7])

In [108]:
#Try out Pytorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication

2. Matrix multiplication(dot product)






https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [110]:
tensor * tensor

tensor([1, 4, 9])

In [111]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [112]:
#Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [113]:
#Matrix Multiplication by hand
1*1 + 2*2 + 3*3

14

In [116]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)

tensor(1)
tensor(5)
tensor(14)
CPU times: user 2.14 ms, sys: 976 µs, total: 3.11 ms
Wall time: 2.79 ms


In [117]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 423 µs, sys: 0 ns, total: 423 µs
Wall time: 336 µs


tensor(14)