<a href="https://colab.research.google.com/github/jai21-7/Introduction-to-Pytorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
print("Hello Im excited to learn PyTorch")

Hello Im excited to learn PyTorch


In [94]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


Introduction to tensors

creating tensor


## Introduction to tensors
###Creating tensors
Pytorch are created using 'torch.Tensor()' -= https://docs.pytorch.org/tutorials/beginner/basics/intro.html

In [95]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [96]:
scalar.ndim

0

In [97]:
#Get tensor back as python int
scalar.item()


7

In [98]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [99]:
vector.ndim

1

In [100]:
vector.shape

torch.Size([2])

In [101]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [102]:
MATRIX.ndim

2

In [103]:
MATRIX[1]

tensor([ 9, 10])

In [104]:
MATRIX.shape



torch.Size([2, 2])

In [105]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6,9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [106]:
TENSOR.ndim

3

In [107]:
TENSOR.shape

torch.Size([1, 3, 3])

In [108]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.



' Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [109]:
# Create a Random tensors of size (3,4)

random_tensor = torch.rand(3, 4)
random_tensor




tensor([[0.1755, 0.5989, 0.1499, 0.4496],
        [0.8833, 0.8364, 0.4491, 0.1985],
        [0.9725, 0.5221, 0.2636, 0.5174]])

In [110]:
random_tensor.ndim

2

In [111]:
# Create a random tensor with  similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim
#


(torch.Size([224, 224, 3]), 3)


https://docs.pytorch.org/tutorials/beginner/pytorch_with_examples.html




In [112]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [113]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [114]:
ones.dtype

torch.float32

In [115]:
random_tensor.dtype


torch.float32

In [116]:
### Creating a range of tensor and tensor-like

In [117]:
# Use torch.range
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
# Use torch.range() and get deprecated message, use torch.arrange
one_to_ten = torch.arange(start=1, end=1111, step=11)
one_to_ten

tensor([   1,   12,   23,   34,   45,   56,   67,   78,   89,  100,  111,  122,
         133,  144,  155,  166,  177,  188,  199,  210,  221,  232,  243,  254,
         265,  276,  287,  298,  309,  320,  331,  342,  353,  364,  375,  386,
         397,  408,  419,  430,  441,  452,  463,  474,  485,  496,  507,  518,
         529,  540,  551,  562,  573,  584,  595,  606,  617,  628,  639,  650,
         661,  672,  683,  694,  705,  716,  727,  738,  749,  760,  771,  782,
         793,  804,  815,  826,  837,  848,  859,  870,  881,  892,  903,  914,
         925,  936,  947,  958,  969,  980,  991, 1002, 1013, 1024, 1035, 1046,
        1057, 1068, 1079, 1090, 1101])

https://docs.pytorch.org/docs/stable/generated/torch.arange.html

In [119]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0])

In [120]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

https://docs.pytorch.org/docs/stable/tensors.html

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:

1. Tensors not right datatype
2. Tensors right device
3. Tensors not on the right device

In [121]:
float_32_tensor.dtype

torch.float32

In [122]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [123]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [124]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [125]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors
1. Tensors not right datatype-to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors right device-to get device from a tensor, can use 'tensor.device'
3. Tensors not on the right device-if tensor is on a different device, can use 'tensor.to(device)'


In [126]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7861, 0.7698, 0.7935, 0.7706],
        [0.6019, 0.0585, 0.6131, 0.8041],
        [0.3470, 0.9480, 0.8926, 0.5066]])

In [127]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7861, 0.7698, 0.7935, 0.7706],
        [0.6019, 0.0585, 0.6131, 0.8041],
        [0.3470, 0.9480, 0.8926, 0.5066]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manipulating Tensors (tensor operations)

Tensor operations include:

.Addition

.Subtraction

.Multiplication(element-wise)

.Division

.Matrix multiplication

In [128]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [129]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [130]:
tensor

tensor([1, 2, 3])

In [131]:
#Substract 10
tensor - 10

tensor([-9, -8, -7])

In [132]:
#Try out Pytorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication

2. Matrix multiplication(dot product)


There are two main rules that performing matrix multiplication needs to satisfy

1. The **inner dimensions** must match:

* ` (3, 2) @ (3, 2)` won't work
* ` (2, 3) @ (3, 2)` will work
* ` (3, 2) @ (2, 3)` will work

The resulting matrix has the shape of the **outer dimensions**:

* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` ->` (3, 3)`


https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [133]:
tensor * tensor

tensor([1, 4, 9])

In [134]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [135]:
#Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [136]:
#Matrix Multiplication by hand
1*1 + 2*2 + 3*3

14

In [137]:
tensor @ tensor

tensor(14)

In [138]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)

tensor(1)
tensor(5)
tensor(14)
CPU times: user 1.92 ms, sys: 0 ns, total: 1.92 ms
Wall time: 1.86 ms


In [139]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 124 µs, sys: 0 ns, total: 124 µs
Wall time: 133 µs


tensor(14)

One of the most common errors in deep learning: shape error

http://matrixmultiplication.xyz/

In [149]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [142]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A transpose switches the axes or dimensions of a given tensor.

In [147]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [146]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [148]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.matmul(tensor_A, tensor_B.T)

Finding the min, max, mean, sum,etc(tensor aggregation)

In [150]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [151]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [152]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [153]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [154]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Finding the positional min and max

In [155]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [157]:
# Find the position in tensor that has the minimum value with argmin() -> return index
x.argmin()

tensor(0)

In [156]:
x[0]

tensor(0)

In [159]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [158]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsequeezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

https://docs.pytorch.org/docs/stable/generated/torch.stack.html

https://docs.pytorch.org/docs/stable/generated/torch.vstack.html

https://docs.pytorch.org/docs/stable/generated/torch.hstack.html

In [162]:
#Let's create a tensor
import torch
x = torch.arange(1., 10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [163]:
# Add a extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [164]:
#Change the view
z=x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [165]:
# Changing z changes x(because a view of a tensor shares the same memory as the orignal)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [166]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [167]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [168]:
x_stacked = torch.stack([x, x, x, x], dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Torch Squeeze

x = torch.zeros(2, 1, 2, 1, 2)

x.size()

y = torch.squeeze(x)

y.size()

y = torch.squeeze(x, 0)

y.size()

y = torch.squeeze(x, 1)

y.size()

y = torch.squeeze(x, (1, 2, 3))





https://docs.pytorch.org/docs/stable/generated/torch.squeeze.html

In [169]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")
#

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [170]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [171]:
x_reshaped.shape

torch.Size([1, 9])

In [172]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [173]:
x_reshaped.squeeze().shape

torch.Size([9])

In [174]:
# torch.permute - rearranges the dimensions of a target tensor in a sprcified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


https://docs.pytorch.org/docs/stable/generated/torch.permute.html

In [175]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

### Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [176]:
#Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [177]:
# Let's index on pur new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [178]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [179]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [180]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [181]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [182]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [183]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [184]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [185]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## PyTorch tensors & Numpy

NumPy is a popular scientific Python numerical computing library.

And because of this ,PyTorch has functionality to interact with it.

* Data in Numpy ,want in PyTorch tensor -> torch.from_numpy(ndarray)

* PyTorch tensor -> Numpy -> torch.Tensor.numpy()


In [186]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [187]:
array.dtype

dtype('float64')

In [188]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [189]:
# Change the value of array ,what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [190]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [191]:
numpy_tensor.dtype

dtype('float32')

In [192]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

https://docs.pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again....

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is "flavour" the randomness

In [193]:
torch.rand(3, 3)

tensor([[0.8099, 0.1825, 0.1594],
        [0.8798, 0.4418, 0.1023],
        [0.3901, 0.7761, 0.1398]])

In [194]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0549, 0.1787, 0.2409, 0.7460],
        [0.3402, 0.0656, 0.7287, 0.4792],
        [0.0103, 0.7790, 0.8825, 0.3739]])
tensor([[0.2333, 0.5384, 0.9817, 0.9632],
        [0.0165, 0.7843, 0.1864, 0.9468],
        [0.3848, 0.7189, 0.0276, 0.7973]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [195]:
1 == 1

True

In [196]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [197]:
torch.manual_seed(RANDOM_SEED)

https://docs.pytorch.org/docs/stable/notes/randomness.html

https://en.wikipedia.org/wiki/Random_seed

## Running  tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers,thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(good).

#### 1.Getting a GPU

1. Easiest - Use Google Colab for a free GPU(options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU,there's lots of options...,see this post for what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/  

3. Use cloud computing - GCP,AWS,Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers(CUDA) takes a little bit of setting up to do this, refer to PyTorch setup documentation
https://pytorch.org/get-started/locally/

2. Check for GPU access with PyTorch

In [198]:
#Check for GPU access with PyTorch
import torch
torch.cuba.is_available()

AttributeError: module 'torch' has no attribute 'cuba'

In [199]:
# Setuup device agnostic  code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [200]:
# Count number of devices
torch.cuda.device_count()

0

https://docs.pytorch.org/docs/stable/notes/cuda.html

###3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [201]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [202]:
# Move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [203]:
# if tensor is on CPU, can't transform it to numpy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [144]:
# TO fix the GPU tensor with NumPy issue ,we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

NameError: name 'tensor_on_gpu' is not defined

In [204]:
tensor_on_gpu

tensor([1, 2, 3])

https://www.learnpytorch.io/00_pytorch_fundamentals/

Visit Exercises

4:12:26