<a href="https://colab.research.google.com/github/jai21-7/Introduction-to-Pytorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello Im excited to learn PyTorch")

Hello Im excited to learn PyTorch


In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


Introduction to tensors

creating tensor


## Introduction to tensors
###Creating tensors
Pytorch are created using 'torch.Tensor()' -= https://docs.pytorch.org/tutorials/beginner/basics/intro.html

In [8]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
#Get tensor back as python int
scalar.item()


7

In [11]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [16]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX[1]

tensor([ 9, 10])

In [20]:
MATRIX.shape



torch.Size([2, 2])

In [22]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6,9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [23]:
TENSOR.ndim

3